import React from 'react';
import { motion } from 'framer-motion';
import { Shield, FileText, Calendar } from 'lucide-react';

const Terms: React.FC = () => {
  const lastUpdated = "December 1, 2024";

  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: [
        "By accessing and using Thread Nova (\"the Service\"), you accept and agree to be bound by the terms and provision of this agreement.",
        "Thread Nova is provided by ThreadFlow Technologies Inc. (\"we\", \"us\", \"our\").",
        "If you do not agree to abide by the above, please do not use this service."
      ]
    },
    {
      title: "2. Description of Service",
      content: [
        "Thread Nova is an AI-powered platform for creating cryptocurrency and Web3 content for social media platforms.",
        "The service includes thread generation, real-time market data integration, analytics, and content management tools.",
        "We reserve the right to modify, suspend, or discontinue any aspect of the service at any time."
      ]
    },
    {
      title: "3. User Accounts and Registration",
      content: [
        "To access certain features, you must register for an account and provide accurate, complete information.",
        "You are responsible for maintaining the confidentiality of your account credentials.",
        "You must notify us immediately of any unauthorized use of your account.",
        "One person or legal entity may not maintain more than one free account."
      ]
    },
    {
      title: "4. Acceptable Use Policy",
      content: [
        "You may not use the service for any illegal or unauthorized purpose.",
        "You may not create content that is defamatory, abusive, harassing, or violates any third-party rights.",
        "You may not attempt to gain unauthorized access to our systems or other users' accounts.",
        "Market manipulation, pump and dump schemes, or fraudulent investment advice is strictly prohibited.",
        "You may not use the service to generate misleading information about cryptocurrency projects."
      ]
    },
    {
      title: "5. Content and Intellectual Property",
      content: [
        "You retain ownership of content you create using our service.",
        "You grant us a limited license to use your content for service improvement and analytics.",
        "Our service, software, and related technology are protected by intellectual property laws.",
        "You may not reverse engineer, copy, or create derivative works of our platform."
      ]
    },
    {
      title: "6. Payment Terms",
      content: [
        "Premium subscriptions are billed in advance on a monthly basis.",
        "All fees are non-refundable except as required by law.",
        "We accept cryptocurrency payments via Coinbase Commerce.",
        "Price changes will be communicated 30 days in advance.",
        "Failure to pay may result in account suspension or termination."
      ]
    },
    {
      title: "7. Data and Privacy",
      content: [
        "We collect and process data in accordance with our Privacy Policy.",
        "We use industry-standard security measures to protect your information.",
        "We may use aggregated, anonymized data for analytics and service improvement.",
        "You may request deletion of your personal data subject to legal and technical limitations."
      ]
    },
    {
      title: "8. Disclaimers and Limitation of Liability",
      content: [
        "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES OF ANY KIND.",
        "We do not guarantee the accuracy of market data or investment advice.",
        "Content generated by our AI should not be considered financial advice.",
        "You are solely responsible for your investment decisions and content creation.",
        "Our liability is limited to the amount you paid for the service in the preceding 12 months."
      ]
    },
    {
      title: "9. Indemnification",
      content: [
        "You agree to indemnify and hold us harmless from any claims arising from your use of the service.",
        "This includes claims related to content you create, distribute, or publish using our platform.",
        "You are responsible for ensuring compliance with all applicable laws and regulations."
      ]
    },
    {
      title: "10. Termination",
      content: [
        "Either party may terminate this agreement at any time.",
        "We may suspend or terminate your account for violation of these terms.",
        "Upon termination, your right to access the service ceases immediately.",
        "Data deletion will occur according to our data retention policies."
      ]
    },
    {
      title: "11. Governing Law",
      content: [
        "These terms are governed by the laws of Delaware, United States.",
        "Any disputes will be resolved through binding arbitration.",
        "The arbitration will be conducted in English in Delaware."
      ]
    },
    {
      title: "12. Changes to Terms",
      content: [
        "We reserve the right to modify these terms at any time.",
        "Material changes will be communicated via email or platform notifications.",
        "Continued use of the service constitutes acceptance of modified terms.",
        "You should review these terms periodically for updates."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-black">
      {/* Background elements */}
      <div className="absolute inset-0 bg-gradient-to-br from-purple-900/20 via-black to-blue-900/20 -z-10"></div>
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-600/10 via-transparent to-transparent -z-10"></div>

      {/* Hero Section */}
      <section className="relative z-10 container mx-auto px-4 sm:px-6 pt-20 sm:pt-24 md:pt-32 pb-16">
        <motion.div 
          className="text-center max-w-4xl mx-auto"
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="mb-6">
            <span className="inline-flex items-center px-4 py-2 rounded-full bg-gradient-to-r from-purple-600/20 to-blue-600/20 border border-purple-500/30 text-purple-300 text-sm font-medium backdrop-blur-sm">
              <FileText className="w-4 h-4 mr-2" />
              Legal Document
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold mb-6 leading-tight">
            <div className="bg-clip-text text-transparent bg-gradient-to-r from-white via-purple-200 to-blue-200">
              Terms of Service
            </div>
          </h1>

          <div className="flex items-center justify-center gap-2 text-gray-400 mb-8">
            <Calendar className="w-4 h-4" />
            <span>Last updated: {lastUpdated}</span>
          </div>

          <p className="text-lg sm:text-xl text-gray-300 mb-8 max-w-3xl mx-auto leading-relaxed">
            Please read these terms of service carefully before using Thread Nova. By using our service, you agree to these terms.
          </p>
        </motion.div>
      </section>

      {/* Terms Content */}
      <section className="relative z-10 py-16">
        <div className="container mx-auto px-4 sm:px-6 max-w-4xl">
          <div className="space-y-12">
            {sections.map((section, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-2xl p-8"
              >
                <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
                  <div className="w-8 h-8 bg-purple-900/30 rounded-lg flex items-center justify-center">
                    <span className="text-purple-400 text-sm font-bold">{index + 1}</span>
                  </div>
                  {section.title}
                </h2>
                
                <div className="space-y-4">
                  {section.content.map((paragraph, pIndex) => (
                    <p key={pIndex} className="text-gray-300 leading-relaxed">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="relative z-10 py-16 sm:py-20">
        <div className="container mx-auto px-4 sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="bg-gradient-to-r from-purple-900/40 to-blue-900/40 backdrop-blur-xl border border-purple-500/30 rounded-3xl p-8 md:p-12">
              <div className="w-16 h-16 bg-purple-900/30 rounded-xl flex items-center justify-center mx-auto mb-6">
                <Shield className="w-8 h-8 text-purple-400" />
              </div>
              
              <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
                Questions About These Terms?
              </h2>
              <p className="text-lg text-gray-300 mb-6">
                If you have any questions about these Terms of Service, please contact our legal team.
              </p>
              
              <motion.a
                href="mailto:legal@threadnova.com"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="px-8 py-4 bg-gradient-to-r from-purple-600 to-blue-600 rounded-xl text-white font-semibold shadow-lg shadow-purple-500/25 hover:shadow-purple-500/40 transition-all duration-300 inline-flex items-center justify-center gap-2"
              >
                <FileText className="w-5 h-5" />
                Contact Legal Team
              </motion.a>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default Terms; 